name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    tags:
      - '*' # Trigger on any tag push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true  # Better to cancel outdated runs

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm # Use pnpm as lock file suggests
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify pnpm version if needed, adjust as necessary

      - name: Install dependencies # Install dependencies using pnpm
        run: pnpm install

      - name: Build static HTML
        id: build # Add an ID to reference the step
        run: pnpm build # Use pnpm build

      - name: Check build status # Add step to check build status
        if: failure() # Run this step only if the previous step failed
        run: |
          echo "::error::Build failed! Stopping workflow."
          exit 1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Make sure this points to where your index.html AND assets are

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
