name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true  # Better to cancel outdated runs

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build static HTML
        run: pnpm build

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Debug dist directory (optional)
        run: find dist -type f | sort  # Lists all files to help debug

      - name: Debug index.html
        run: |
          echo "Examining index.html for asset references:"
          grep -n "index-" dist/index.html
          echo "Current GitHub repository name: $GITHUB_REPOSITORY"

      - name: Verify asset paths in index.html
        run: |
          echo "Checking if paths were updated correctly:"
          cat dist/index.html | grep -E 'src="|href="' | grep -v "data:" | grep -v "favicon"

      - name: Fix asset paths in index.html
        run: |
          echo "Fixing absolute paths in index.html"
          sed -i 's|src="/assets/|src="./assets/|g' dist/index.html
          sed -i 's|href="/assets/|href="./assets/|g' dist/index.html
          cat dist/index.html | grep -E 'src="|href="' | grep -v "data:" | grep -v "favicon"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Make sure this points to where your index.html AND assets are

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
